version: '3'
services:
  gin:
    build:
      dockerfile: ./docker/dev/Dockerfile
      context: .
    tty: true
    volumes: 
    - .:/src
    ports:
    - 8000:8080
    command: 
      sh -c 'air -c .air.toml'
