version: "3"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-CU11-ubuntu
    container_name: mssql-test
    ports:
      - "11433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password
      - MSSQL_PID=Express
      - MSSQL_LCID=1041
      - MSSQL_COLLATION=Japanese_CI_AS