version: '3'

services:
  app:
    container_name: fastapi_practice
    build: ./app
    env_file: .env
    networks:
      - nginx_network
    command: gunicorn main:app -b 0.0.0.0:5000

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge